### ISSUE TITLE
meta_description tweaks

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern-documentation#6]
[[format]]="boolean"

Should be:

    [[format]]="value" (or 'string' or something like that)

Also, the `type` attribute needs adding, along with examples. I can write the examples if you like, or you can cobble some together from [my post about it on the forum](http://forum.textpattern.com/viewtopic.php?pid=291772#p291772) if you wish (though the `format` attribute as documented there is wrong).

**Comment by philwareham** [comment]
Hi,

Can you amend? You probably know better than I since you coded them anyway. You can edit directly within GitHub site if that's easier than cloning/forking/whatever.

I also just realised that it's worth stating that the description field is content sensitive and not just for the article Write page.

**Comment by Bloke** [comment]
Sure yeah. Wasn't sure if I had commit access or not here. Probably have, should have checked first.

**Comment by philwareham** [comment]
You do, it's part of the Textpattern dev group repos.

**Comment by Bloke** [comment]
Closed by 5918df88f18528b3afd9f637cb6e32b4e8526cdd
